"vi": {
                "app_title": "Hệ thống Nông nghiệp Thông minh",
                "system_title": "Hệ thống quản lý nông nghiệp thông minh",
                "username": "Tên đăng nhập",
                "password": "Mật khẩu",
                "login": "Đăng nhập",
                "show_password": "Hiện mật khẩu",
                "settings": "Cài đặt",
                "logout": "Đăng xuất",
                "weather": "Thời tiết",
                "watering": "Tưới nước",
                "home": "Trang chủ",
                "monday": "Thứ hai",
                "tuesday": "Thứ ba",
                "wednesday": "Thứ tư",
                "thursday": "Thứ năm",
                "friday": "Thứ sáu",
                "saturday": "Thứ bảy",
                "sunday": "Chủ nhật",
                "temperature": "Nhiệt độ",
                "humidity": "Độ ẩm",
                "cloud": "Mây",
                "precipitation": "Kết tủa",
                "wind_speed": "Sức gió",
                "language": "Ngôn ngữ",
                "interface": "Giao diện",
                "performance": "Hiệu suất",
                "help": "Trợ giúp",
                "notifications": "Thông báo",
                "personal_info": "Thông tin cá nhân",
                "pin":"Chân cắm",
                "version": "Phiên bản 1.0.0",
                "save": "Lưu thay đổi",
                "cancel": "Hủy",
                "error": "Lỗi",
                "success": "Thành công",
                "current_password": "Mật khẩu hiện tại",
                "new_password": "Mật khẩu mới",
                "confirm_password": "Xác nhận mật khẩu mới",
                "email": "Email",
                "invalid_email": "Email không hợp lệ",
                "password_mismatch": "Mật khẩu mới không khớp",
                "password_length": "Mật khẩu mới phải có ít nhất 4 ký tự",
                "wrong_password": "Mật khẩu hiện tại không đúng",
                "update_success": "Đã cập nhật thông tin tài khoản",
                "rain_prob": "Xác suất mưa",
                "loading": "Đang tải",
                "updating_weather": "Đang cập nhật thông tin thời tiết...",
                "weather_error": "Lỗi khi cập nhật thông tin thời tiết",
                "error": "Lỗi",
                "yesterday": "Hôm qua",
                "today": "Hôm nay",
                "next_day": "ngày tiếp theo",
                "sunny": "Nắng",
                "rainy": "Mưa",
                "watering_options": "Tùy chọn tưới nước",
                "manual_watering": "Tưới thủ công",
                "auto_watering": "Tưới tự động",
                "manual_watering_desc": "Điều khiển trực tiếp việc tưới nước",
                "auto_watering_desc": "Tự động tưới theo lịch trình",
                "system_on": "Hệ thống đang BẬT",
                "system_off": "Hệ thống đang TẮT",
                "on": "BẬT",
                "off": "TẮT",
                "back": "Quay lại",
                "auto_watering_title": "Cài đặt tưới tự động",
                "auto_system_on": "Hệ thống tưới tự động đang BẬT",
                "auto_system_off": "Hệ thống tưới tự động đang TẮT",
                "auto_watering_settings": "Cài đặt tưới tự động",
                "start_time_label": "Thời gian bắt đầu:",
                "end_time_label": "Thời gian kết thúc:",
                "cycle_label": "Chu kỳ tưới:",
                "duration_label": "Thời gian mỗi lần tưới:",
                "minutes": "phút",
                "cycle_30min": "30 phút một lần",
                "cycle_1hour": "1 giờ một lần",
                "cycle_2hours": "2 giờ một lần",
                "cycle_4hours": "4 giờ một lần",
                "operating_time": "Thời gian hoạt động:",
                "watering_cycle": "Chu kỳ tưới:",
                "watering_duration": "Thời gian tưới:",
                "back_btn": "Quay lại",
                "activate_btn": "Kích hoạt",
                "deactivate_btn": "Vô hiệu hóa",
                "invalid_credentials": "Tên đăng nhập hoặc mật khẩu không đúng!",
                "login_success": "Đăng nhập thành công!",
                "select_language": "Chọn ngôn ngữ",
                "language_changed": "Đã thay đổi ngôn ngữ thành",
                "please_fill_all": "Vui lòng điền đầy đủ thông tin!",
            },
            "en": {
                "app_title": "Smart Agriculture System",
                "system_title": "Smart Agriculture Management System",
                "username": "Username",
                "password": "Password",
                "login": "Login",
                "show_password": "Show password",
                "settings": "Settings",
                "logout": "Logout",
                "weather": "Weather",
                "watering": "Watering",
                "home": "Home",
                "monday": "Monday",
                "tuesday": "Tuesday",
                "wednesday": "Wednesday",
                "thursday": "Thursday",
                "friday": "Friday",
                "saturday": "Saturday",
                "sunday": "Sunday",
                "temperature": "Temperature",
                "select_language": "Select Language",
                "language":"Language",
                "interface": "Interface",
                "help":"Help",
                "personal_info": "Personal Information",
                "notifications": "Notifications",
                "temperature": "Temperature",
                "wind_speed": "Wind Speed",
                "humidity": "Humidity",
                "precipitation": "Precipitation",
                "select_language": "Select Language",
                "humidity": "Humidity",
                "cloud": "Cloud",
                "rain_prob": "Rain Probability",
                "loading": "Loading",
                "updating_weather": "Updating weather information...",
                "weather_error": "Error updating weather information",
                "error": "Error",
                "yesterday": "Yesterday",
                "today": "Today",
                "next_day": "Next day",
                "sunny": "Sunny",
                "rainy": "Rainy",
                "watering_options": "Watering Options",
                "manual_watering": "Manual Watering",
                "auto_watering": "Automatic Watering",
                "manual_watering_desc": "Direct control of watering",
                "auto_watering_desc": "Automatic watering on schedule",
                "system_on": "System is ON",
                "system_off": "System is OFF",
                "on": "ON",
                "off": "OFF",
                "back": "Back",
                "auto_watering_title": "Automatic Watering Settings",
                "auto_system_on": "Automatic Watering System is ON",
                "auto_system_off": "Automatic Watering System is OFF",
                "auto_watering_settings": "Automatic Watering Settings",
                "start_time_label": "Start Time:",
                "end_time_label": "End Time:",
                "cycle_label": "Watering Cycle:",
                "duration_label": "Watering Duration:",
                "minutes": "minutes",
                "cycle_30min": "Every 30 minutes",
                "cycle_1hour": "Every hour",
                "cycle_2hours": "Every 2 hours",
                "cycle_4hours": "Every 4 hours",
                "operating_time": "Operating Time:",
                "watering_cycle": "Watering Cycle:",
                "watering_duration": "Watering Duration:",
                "back_btn": "Back",
                "activate_btn": "Activate",
                "deactivate_btn": "Deactivate",
                "pin":"Pin",
                "version": "Version 1.0.0",
                "please_fill_all": "Please fill in all fields!",
                "invalid_credentials": "Invalid username or password!",
                "login_success": "Login successful!",   
                "language_changed": "Language changed to",
            }